### ISSUE TITLE
More graphs 

### ISSUE THREAD

**Issue by ghost** [gzachos/rpi-airtemp#2]
Could we have more graphs?

Maybe 6 months and 12 months. I use this script for weather temperature but it don't log the year.

Thanks

**Comment by gzachos** [comment]
The 32140800 (= 12months * 31days * 24hours * 60min * 60sec) most recent values are logged in the database. That means that the data are there (if the script has been running for long enough) but are not graphed. I didn't add 6 and 12 month graphs because it would take more time for the script to execute and it is very simple for someone to add new graphs.

**Adding/Removing Graphs**
Just edit the `INTERVALS` and `TITLES` variables on lines `68` and `69` respectively in file `temp-graph.sh` ([link](https://github.com/gzachos/rpi-airtemp/blob/master/temp-graph.sh)). Adding a 6 and 12 month graph requires updating those two lines to match:
```
INTERVALS="1h 2h 4h 12h 24h 1w 4w 12w 24w 1y"
TITLES=('1 Hour' '2 Hour' '4 Hour' '12 Hour' '24 Hour' '1 Week' '1 Month' '3 Month' '6 Month' '1 Year')
```
To remove a graph, simply remove the corresponding entries in those two variables.

**Comment by gzachos** [comment]
The 32140800 (= 12months * 31days * 24hours * 60min * 60sec) most recent values are logged in the database. That means that the data are there (if the script has been running for long enough) but are not graphed. I didn't add 6 and 12 month graphs because it would take more time for the script to execute and it is quite simple for someone to add new graphs. Nevertheless, I am going to add the 6-month and 1-year graphs.
