### ISSUE TITLE
Minus turns into m

### ISSUE THREAD

**Issue by TwinUsers** [gzachos/rpi-airtemp#3]
When going below 0 degrees it starts becoming M?

See attached picture
![D755146A-9297-467F-9B72-1F5B0EA6B823](https://user-images.githubusercontent.com/11603109/103181182-4b446580-4896-11eb-9086-e43257f66eef.png)

**Comment by gzachos** [comment]
@TwinUsers This is an ```rrdtool``` feature for readability purposes. Character ```m``` stands for **milli** (10^-3).  Are the values provided that small (i.e. -176.67 m = -176.67 * 10^- 3 = -0.17667 Celsius)? You can use ```--units-exponent 0``` as an option to the ```rrdtool graph``` command  to prevent any scaling of the y-axis values.

**Comment by TwinUsers** [comment]
I’ll check tonight if it drops again, when it hits minus 1c is states -1.08c etc

**Comment by gzachos** [comment]
I replicated this issue and I can verify ```--units-exponent 0``` resolved it (left vs right y-axis in attached photo). For now I am going to skip adding this option to the ```rrdtool graph``` command. This issue seems help readability in places with slow or small temperature variations (i.e. a freezer).
![01-temp-2h](https://user-images.githubusercontent.com/8009725/104831549-b3350d00-5892-11eb-8c86-96943286f5d6.png)
